version: '2'

services:
  frontend:
    image: cgbudockerdev1.us.oracle.com:7755/amplify/ui-component
    ports:
      - "8001"

    volumes:
      - ./src:/usr/src/app/src
      - ./web:/usr/src/app/web
      - ./test:/usr/src/app/test
      - ./template:/usr/src/app/template
      - ./reports:/usr/src/app/reports
      - ./package.json:/usr/src/app/package.json
      - ./karma.conf.js:/usr/src/app/karma.conf.js
      - ./test-main.js:/usr/src/app/test-main.js
      - ./gulpfile.js:/usr/src/app/gulpfile.js
