version: '2'

services:
    component-server:
        image: cgbudockerdev1.us.oracle.com:7755/amplify/ui-component-server

    frontend:
        image: cgbudockerdev1.us.oracle.com:7755/amplify/ui-component/ringette-web


    selenium-ff:
        image:  selenium/standalone-firefox-debug:3.0.0-dubnium
        links:
            - frontend
        environment:
            - no_proxy=localhost,frontend

    selenium-ch:
        image:  selenium/standalone-chrome-debug:3.0.0-dubnium
        links:
            - frontend
        environment:
            - no_proxy=localhost,frontend
    test:
        image: cgbudockerdev1.us.oracle.com:7755/amplify/ui-component/ringette-web/cucumber
        links:
            - selenium-ff
            - selenium-ch
        depends_on:
            - selenium-ff
            - selenium-ch
            - frontend
        environment:
            - no_proxy=localhost,selenium-ff,selenium-ch
